// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXVNVF3HoEs_VYhrGmJYVhCg9-weT1Yw',
    appId: '1:376512958685:web:7bb178028cb648b4ae8b34',
    messagingSenderId: '376512958685',
    projectId: 'fluttercalculator-8fe21',
    authDomain: 'fluttercalculator-8fe21.firebaseapp.com',
    storageBucket: 'fluttercalculator-8fe21.firebasestorage.app',
    measurementId: 'G-S5W7C2JEGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSeBnxNsVzxaajzR5Y9udZOhwHndqfy2o',
    appId: '1:376512958685:android:b1fe79058a2f74b8ae8b34',
    messagingSenderId: '376512958685',
    projectId: 'fluttercalculator-8fe21',
    storageBucket: 'fluttercalculator-8fe21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCxHLO6YkKfy1Rz5lruP9d7ohqwfPFUnk',
    appId: '1:376512958685:ios:04552dba586d953cae8b34',
    messagingSenderId: '376512958685',
    projectId: 'fluttercalculator-8fe21',
    storageBucket: 'fluttercalculator-8fe21.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCxHLO6YkKfy1Rz5lruP9d7ohqwfPFUnk',
    appId: '1:376512958685:ios:04552dba586d953cae8b34',
    messagingSenderId: '376512958685',
    projectId: 'fluttercalculator-8fe21',
    storageBucket: 'fluttercalculator-8fe21.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlXVNVF3HoEs_VYhrGmJYVhCg9-weT1Yw',
    appId: '1:376512958685:web:ed9b3c5e7c4e455bae8b34',
    messagingSenderId: '376512958685',
    projectId: 'fluttercalculator-8fe21',
    authDomain: 'fluttercalculator-8fe21.firebaseapp.com',
    storageBucket: 'fluttercalculator-8fe21.firebasestorage.app',
    measurementId: 'G-SX0FTVWT6N',
  );
}
